# This is a full example of how to run the echo actor exposed with an HTTP server. Using this
# example requires you to have WADM running: https://github.com/wasmCloud/wadm/.
#
# To run this example, use: `wash app deploy wadm.yaml`

apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: hello
  annotations:
    version: v0.0.44
    description: "wasmCloud Hello World Example"
spec:
  components:
    - name: hello
      type: actor
      properties:
        image: file:///home/jt117/labs/wasmcloud_infra/hello-world/build/hello_world_s.wasm
      traits:
        - type: spreadscaler
          properties:
            replicas: 50
#            spread:
#              - name: host1
#                requirements:
#                  host: "189"
#                weight: 40
#              - name: host2
#                requirements:
#                  host: "190"
#                weight: 20
#              - name: host3
#                requirements:
#                  host: "191"
#                weight: 40
        - type: linkdef
          properties:
            target: httpserver
            values:
              address: 0.0.0.0:8080

    - name: httpserver
      type: capability
      properties:
        image: file:///home/jt117/labs/wasmcloud_infra/capability-providers/httpserver-rs/build/httpserver.par.gz
        contract: wasmcloud:httpserver
